name: Check links

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  linkchecker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # 7.0.1
        with:
          persist-credentials: false  # since the next step does not need it

      - name: Start 11ty dev server
        id: server
        run: npm start
        background: true

      - name: Install linkchecker
        run: pip install linkchecker

      - name: Run linkchecker
        run: linkchecker --check-extern -v http://localhost:8080
